### ISSUE TITLE
Upgrade Map button

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA-Resources#188]
Essentially `mono --debug OpenRA.Utility.exe --upgrade-map $name.oramap 20131223` maybe with a dropdown box of the latest releases (that is still user-editable). This may seem simple, but is probably going to help mappers a lot like https://github.com/OpenRA/OpenRA-Resources/issues/139 already did as using the command line is not common knowledge for Windows users and what version string to use is often not understood (it has to be the source version, not the destination).

**Comment by ihptru** [comment]
implemented. 
![sn103](https://cloud.githubusercontent.com/assets/791864/13984468/640c17ac-f107-11e5-86fd-6429003c4315.png)
