### ISSUE TITLE
Create statistics from user uploaded replays

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA-Resources#192]
We now have meta-data attached to replays https://github.com/OpenRA/OpenRA/pull/5215 that tell us who played what faction and who won the game. This gives us an opportunity to collect statistics like http://ns2stats.com/all/index which faction wins the most, which maps are popular and how long the rounds are. This way we get some hard evidence to optimize balancing instead of using gut feeling.

**Comment by Mailaender** [comment]
Depends on https://github.com/OpenRA/OpenRA-Resources/issues/253.

**Comment by penev92** [comment]
So a ranking based only on replays uploaded by players? That doesn't sound right. What if we have the servers send the information the the resource site instead?
Maybe have an option to play "ranked" or "unranked", and if you play "ranked", then the statistics from that match get sent to the resource site by the server.

**Comment by ihptru** [comment]
@penev92 sounds right for dedicated servers.

**Comment by ihptru** [comment]
Replays support is gone.
But here is another interesting project which gathers games and players stats: http://www.openra.club
