### ISSUE TITLE
Avoid NonCommercial licenses

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA-Resources#244]
via https://github.com/OpenRA/OpenRA/issues/6862: ideally there should be no choice for a CC-*-NC license and especially it should not be the default selection so people who don't care use it. Non-Commercial licenses are not only incompatible with the OpenRA license, but bad ideas in general. https://en.wikipedia.org/wiki/Creative_Commons#Other_criticism_of_the_non-commercial_license

**Comment by ihptru** [comment]
It's been a while as license is not forced, and people anyway keep choosing one or another version of Creative Common; also I am getting requests like 'ability to change license' after uploading as they forgot to define one in the first place.

**Comment by Mailaender** [comment]
Yes, http://resource.openra.net/maps/2173 does not sound like people are too happen with your default NC license choice.

**Comment by ihptru** [comment]
as said, it's not default for more then 3 months already

**Comment by Mailaender** [comment]
Did you remove the license feature completely now?

**Comment by ihptru** [comment]
no I will leave it as it is

**Comment by ihptru** [comment]
No. So it's required to remove licensing completely?

**Comment by Mailaender** [comment]
Well, no. That is somehow my personal opinion. However we can't include NC maps in OpenRA. Not everyone may not that. At least don't make it a default option please so people that don't care, choose a compatible open content license.
