### ISSUE TITLE
wish:read new comments

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA-Resources#246]
The site is turning really well, but I want to see all new comments..

**Comment by ihptru** [comment]
https://github.com/OpenRA/OpenRA-Resources/commit/c2a6823699be9c7d77f14d9833cf0ffce9b1093c

![sn115](https://cloud.githubusercontent.com/assets/791864/12349060/c11de96c-bb7d-11e5-8aad-7c3f4eeebb00.png)

#40
