### ISSUE TITLE
Maps: Add tags

### ISSUE THREAD

**Issue by GeertJohan** [OpenRA/OpenRA-Resources#252]
I suggest creating a list of available tags that can be set on a map. These tags can be in different categories:
- Gameplay
- Layout
 - realistic
 - chaos (small map with lots of resources)
 - symmetrical
- etc

A tagging system needs to be implemented once and can be used for multiple purposes. But then maybe you want more control over these attributes and create separate filters for each one of them.

Related to  #193, the tag system can be used to add types like this.

**Comment by UberWaffe** [comment]
The request in #281 is for mod specific filtering. As long as mod specific tags are also agreed on then that should also be covered.

**Comment by ihptru** [comment]
MapFormat 11 in next release also replaces map's `Type` with `Categories`. There can be set multiple categories on single map. Resource Center already supports such maps.

**Comment by ihptru** [comment]
Implemented filter by Categories, Lobby also will allow filtering maps by Categories.
All additional tags can be added to `Categories:` in map.yaml and no need to implement a duplicate functionality on Resource Center.
