### ISSUE TITLE
Replay sharing

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA-Resources#253]
Allow people to upload replay files and parse it with https://github.com/OpenRA/OpenRA/pull/7458 to display meta data.

**Comment by Mailaender** [comment]
Not required anymore since http://www.gamereplays.org/openra/portals.php?show=news&news_id=965839

**Comment by ihptru** [comment]
As their site is so popular, maybe try to help them improve their replay uploading and parsing.
Without perspectives on Resource Center, just removed Replays support completely.
