### ISSUE TITLE
Update the maps to the current format

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA-Resources#259]
Some maps have changed in the OpenRA distribution, but not on the replay site so some hashes are not found there. http://www.gamereplays.org/community/index.php?s=&showtopic=965411&view=findpost&p=9804485

**Comment by ihptru** [comment]
ts:
http://resource.openra.net/maps/8128/
http://resource.openra.net/maps/8129/
http://resource.openra.net/maps/8130/
http://resource.openra.net/maps/8131/
http://resource.openra.net/maps/8132/

d2k:
http://resource.openra.net/maps/8133/
http://resource.openra.net/maps/8134/
http://resource.openra.net/maps/8135/
http://resource.openra.net/maps/8136/
http://resource.openra.net/maps/8137/
http://resource.openra.net/maps/8138/
http://resource.openra.net/maps/8139/
http://resource.openra.net/maps/8140/
http://resource.openra.net/maps/8141/
http://resource.openra.net/maps/8143/
http://resource.openra.net/maps/8144/
http://resource.openra.net/maps/8145/
http://resource.openra.net/maps/8146/
http://resource.openra.net/maps/8147/
http://resource.openra.net/maps/8148/
http://resource.openra.net/maps/8149/
http://resource.openra.net/maps/8150/
http://resource.openra.net/maps/8151/

cnc:
http://resource.openra.net/maps/8152/
http://resource.openra.net/maps/8153/
http://resource.openra.net/maps/8154/
http://resource.openra.net/maps/1403/
http://resource.openra.net/maps/4575/
http://resource.openra.net/maps/4711/
http://resource.openra.net/maps/4605/
http://resource.openra.net/maps/8156/
http://resource.openra.net/maps/4609/
http://resource.openra.net/maps/4864/
http://resource.openra.net/maps/8158/
http://resource.openra.net/maps/4733/
http://resource.openra.net/maps/8161/
http://resource.openra.net/maps/5436/
http://resource.openra.net/maps/8163/
http://resource.openra.net/maps/8164/
http://resource.openra.net/maps/2647/
http://resource.openra.net/maps/1388/
http://resource.openra.net/maps/8167/
http://resource.openra.net/maps/4764/
http://resource.openra.net/maps/8169/
http://resource.openra.net/maps/5379/
http://resource.openra.net/maps/5514/
http://resource.openra.net/maps/8171/
http://resource.openra.net/maps/8172/
http://resource.openra.net/maps/8173/
http://resource.openra.net/maps/8175/
http://resource.openra.net/maps/8177/
http://resource.openra.net/maps/8179/
http://resource.openra.net/maps/4568/
http://resource.openra.net/maps/5884/
http://resource.openra.net/maps/8181/
http://resource.openra.net/maps/8182/
http://resource.openra.net/maps/4734/
http://resource.openra.net/maps/4795/
http://resource.openra.net/maps/5335/
http://resource.openra.net/maps/8185/
http://resource.openra.net/maps/8186/
http://resource.openra.net/maps/2702/
http://resource.openra.net/maps/5858/
http://resource.openra.net/maps/5913/
http://resource.openra.net/maps/8190/
http://resource.openra.net/maps/8191/
http://resource.openra.net/maps/8192/
http://resource.openra.net/maps/8193/
http://resource.openra.net/maps/8194/
http://resource.openra.net/maps/8195/
http://resource.openra.net/maps/8196/
http://resource.openra.net/maps/8197/
http://resource.openra.net/maps/8198/
http://resource.openra.net/maps/8199/
http://resource.openra.net/maps/8200/
http://resource.openra.net/maps/8201/
http://resource.openra.net/maps/8202/
http://resource.openra.net/maps/8203/
http://resource.openra.net/maps/8204/
http://resource.openra.net/maps/8205/
http://resource.openra.net/maps/8206/
http://resource.openra.net/maps/8207/
http://resource.openra.net/maps/8208/
http://resource.openra.net/maps/8209/
http://resource.openra.net/maps/8210/
http://resource.openra.net/maps/8211/
http://resource.openra.net/maps/8212/
http://resource.openra.net/maps/8213/

**Comment by ihptru** [comment]
## release-20151224

ra  (part 1/2, extracted only):
```
http://resource.openra.net/maps/8214/
http://resource.openra.net/maps/8215/
http://resource.openra.net/maps/8216/
http://resource.openra.net/maps/8217/
http://resource.openra.net/maps/8218/
http://resource.openra.net/maps/8219/
http://resource.openra.net/maps/8220/
http://resource.openra.net/maps/8221/
http://resource.openra.net/maps/8222/
http://resource.openra.net/maps/8223/
http://resource.openra.net/maps/8224/
http://resource.openra.net/maps/8225/
http://resource.openra.net/maps/8226/
http://resource.openra.net/maps/8227/
http://resource.openra.net/maps/8228/
http://resource.openra.net/maps/8229/
http://resource.openra.net/maps/8230/
http://resource.openra.net/maps/8231/
http://resource.openra.net/maps/8232/
http://resource.openra.net/maps/8233/
http://resource.openra.net/maps/8234/
http://resource.openra.net/maps/8235/
http://resource.openra.net/maps/8236/
http://resource.openra.net/maps/8237/
http://resource.openra.net/maps/8238/
http://resource.openra.net/maps/8239/
http://resource.openra.net/maps/8240/
http://resource.openra.net/maps/8241/
http://resource.openra.net/maps/8242/
http://resource.openra.net/maps/8243/
http://resource.openra.net/maps/8244/
```

**Comment by ihptru** [comment]
## release-20151224

ra  (part 2/2, compressed only):
```
http://resource.openra.net/maps/5337/
http://resource.openra.net/maps/5754/
http://resource.openra.net/maps/4603/
http://resource.openra.net/maps/4875/
http://resource.openra.net/maps/5470/
http://resource.openra.net/maps/5080/
http://resource.openra.net/maps/5763/
http://resource.openra.net/maps/4584/
http://resource.openra.net/maps/4585/
http://resource.openra.net/maps/5244/
http://resource.openra.net/maps/4885/
http://resource.openra.net/maps/6421/
http://resource.openra.net/maps/5240/
http://resource.openra.net/maps/4570/
http://resource.openra.net/maps/4651/
http://resource.openra.net/maps/4970/
http://resource.openra.net/maps/4732/
http://resource.openra.net/maps/4573/
http://resource.openra.net/maps/4693/
http://resource.openra.net/maps/4577/
http://resource.openra.net/maps/5221/
http://resource.openra.net/maps/4954/
http://resource.openra.net/maps/4945/
http://resource.openra.net/maps/4790/
http://resource.openra.net/maps/4756/
http://resource.openra.net/maps/3727/
http://resource.openra.net/maps/4607/
http://resource.openra.net/maps/4576/
http://resource.openra.net/maps/4744/
http://resource.openra.net/maps/4840/
http://resource.openra.net/maps/4649/
http://resource.openra.net/maps/4582/
http://resource.openra.net/maps/4589/
http://resource.openra.net/maps/4633/
http://resource.openra.net/maps/4592/
http://resource.openra.net/maps/4904/
http://resource.openra.net/maps/4580/
http://resource.openra.net/maps/5185/
http://resource.openra.net/maps/4832/
http://resource.openra.net/maps/4727/
http://resource.openra.net/maps/5101/
http://resource.openra.net/maps/3977/
http://resource.openra.net/maps/5259/
http://resource.openra.net/maps/4587/
http://resource.openra.net/maps/5085/
http://resource.openra.net/maps/5111/
http://resource.openra.net/maps/4768/
http://resource.openra.net/maps/4849/
http://resource.openra.net/maps/5095/
http://resource.openra.net/maps/8257/
http://resource.openra.net/maps/4578/
http://resource.openra.net/maps/8258/
http://resource.openra.net/maps/3683/
http://resource.openra.net/maps/5565/
http://resource.openra.net/maps/4453/
http://resource.openra.net/maps/8260/
http://resource.openra.net/maps/5271/
http://resource.openra.net/maps/5752/
http://resource.openra.net/maps/4571/
```
