### ISSUE TITLE
Replays link

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA-Resources#260]
Since replays are hosted here: 
http://www.gamereplays.org/openra/replays.php?game=92&tab=popular&show=index&tab_new=upcoming&display_mode=standard

I think we can now add this URL to the the http://resource.openra.net/Other/Replays link on the resource site.

![other_replays](https://cloud.githubusercontent.com/assets/1732773/8892952/1517b620-3379-11e5-97e7-4e586a7e59b4.png)

**Comment by ihptru** [comment]
![sn90](https://cloud.githubusercontent.com/assets/791864/9980932/15e5f22a-5fb5-11e5-89df-1a3cd1ef6955.png)

**Comment by x-a-n-a-x** [comment]
I don't see this footer.. (even if I just visit the website or if I am logged in).

Btw, I think adding this link in a footer (at the bottom) like this makes it harder for visitors to find the link. That's why I suggest to place it at the top, in the (currently) disabled menu.

**Comment by ihptru** [comment]
screenshot is taken from Replays page which is hidden. I've already made uploading and parsing replays. I am fighting for time to make 2 page to display them (all replays and detail page)

**Comment by ihptru** [comment]
http://resource.openra.net/replays/
