### ISSUE TITLE
Show rules is not showing all yaml

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA-Resources#264]
All of yaml is not displayed.. just some part....

**Comment by kyrreso** [comment]
only some part of the yaml is displayed.

**Comment by kyrreso** [comment]
at least it should show options....

**Comment by ihptru** [comment]
Click 'show yaml' to see full yaml

**Comment by ihptru** [comment]
I think all user needs are covered by Showing Rules and Showing Yaml.
