### ISSUE TITLE
Add map_grid_type field to the remote map metadata API

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA-Resources#265]
This field should contain the value of the mod's MapGrid: Type: field.  This is defined per-mod, but we need this specified in the map data so that we can properly render the spawn points for mods that aren't installed.

The current values are `Rectangular` for ra/td/d2k, and `Isometric` for ts.  This will change to `Rectangular` for ra/td/d2k and `RectangularIsometric` for ts after https://github.com/OpenRA/OpenRA/pull/9526/ is merged.

**Comment by ihptru** [comment]
Please check

**Comment by penev92** [comment]
This wont work for thirdparty mods, unless you manually add them to the list though.

**Comment by ihptru** [comment]
Any idea how to automate definition of map_grid_type from .oramap?

**Comment by pchote** [comment]
The way I would do it is to add support for custom mod definitions where they can upload their tilesets and set some additional metadata (mod name, details, grid type, etc).  These entries can then be queried when parsing a map.

**Comment by penev92** [comment]
So in other words not fixable until we have thirdparty mod hosting on the resource site.

**Comment by pchote** [comment]
I'm suggesting that as an interim measure we add very limited support with a fixed set of manually entered metadata, plus uploading the tileset yaml.
