### ISSUE TITLE
Maps with 0 players

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA-Resources#268]
I don't know if it's intended (tests ?) but the maps 809, 810, 1314, 1405, 1478, 1765, 1845, 1971, 2388, 2420, 2617, 2831, 2882, 2883, 2884, 2961, 3008, 3009, 3010, 3077, 3080, 3093, 3102, 3245, 3738, 4333, 4632, 5146, 5209, 5416, 5498, 6053 and 6203 are 0 players maps.
If not is it possible to check the number of players when the map is uploaded ?

**Comment by ihptru** [comment]
this maps are really 0 players maps.
In most cases it's a mistake of map author when he uploads.
I checked several maps and found that authors uploaded newer revisions of their maps where players are set.

So,
1) it can be mistake of author and he uploads new revision without removing older one.
2) author just checks that map can be uploaded and parsed when it's not yet finished. (some authors actually finish their maps and some not).
3) Without checking all IDs you mentioned, possibly some maps can be Missions. I think missions can be ok without player references at all.

btw, just interested, how did you find all this IDs ?


Example of player reference from map.yaml:

```
Players:
	PlayerReference@Neutral:
		Name: Neutral
		OwnsWorld: True
		NonCombatant: True
		Faction: england
	PlayerReference@Creeps:
		Name: Creeps
		NonCombatant: True
		Faction: england
	PlayerReference@Multi0:
		Name: Multi0
		Playable: True
		Faction: Random
		Enemies: Creeps
	PlayerReference@Multi1:
		Name: Multi1
		Playable: True
		Faction: Random
		Enemies: Creeps
	PlayerReference@Multi2:
		Name: Multi2
		Playable: True
		Faction: Random
		Enemies: Creeps
	PlayerReference@Multi3:
		Name: Multi3
		Playable: True
		Faction: Random
		Enemies: Creeps
	PlayerReference@Multi4:
		Name: Multi4
		Playable: True
		Faction: Random
		Enemies: Creeps
	PlayerReference@Multi5:
		Name: Multi5
		Playable: True
		Faction: Random
		Enemies: Creeps
	PlayerReference@Multi6:
		Name: Multi6
		Playable: True
		Faction: Random
		Enemies: Creeps
	PlayerReference@Multi7:
		Name: Multi7
		Playable: True
		Faction: Random
		Enemies: Creeps
```

Starts from ```PlayerReference@Multi0:```

**Comment by StexoO** [comment]
Oh ok, so it's definitely not an issue.
I was looking for the biggest maps with the most players to test the latest playtest, so I needed to browse all the maps and read the number of players of every map, so I wrote a little tool who told me there was 0 players maps.

**Comment by ihptru** [comment]
also Shellmaps are mostly with 0 players
