### ISSUE TITLE
Display more maps on 'highest rated', 'most viewed', etc

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA-Resources#269]
Copied from https://github.com/OpenRA/OpenRA/pull/10343:

> In the resource center there are buttons to select the highest rated map, the most viewed map, etc. When this is clicked it shows only the top result. It would be great if it would show a full page (or even more?) of sorted maps for the selected characteristic.

cc: @noobmapmaker

**Comment by noobmapmaker** [comment]
Thanks for moving! Apologies for wrongly adding :)

**Comment by ihptru** [comment]
fixed, covered by 'sort by' box.
