### ISSUE TITLE
Add link to LUA basic learning guide to Wiki

### ISSUE THREAD

**Issue by noobmapmaker** [OpenRA/OpenRA-Resources#270]
LUA.org has a great resource to learn the basics of LUA: http://www.lua.org/pil/contents.html#P1

It would be nice to add it to the sidebar of the wiki: https://github.com/OpenRA/OpenRA/wiki/Lua-API

**Comment by abcdefg30** [comment]
I added a small note on the [`Map Scripting`](https://github.com/OpenRA/OpenRA/wiki/Map-scripting/_compare/82f26be0276f7e932ce8f908b871990dc8f0620c...6b90d327d11253ae309197733d7498272853ec5d) page.

**Comment by abcdefg30** [comment]
I filed https://github.com/OpenRA/OpenRA/pull/10414 now.
