### ISSUE TITLE
Support CC-BY-SA as a license choice, and fix old uploads.

### ISSUE THREAD

**Issue by chrisforbes** [OpenRA/OpenRA-Resources#275]
I was disappointed to find that the resource site is claiming to offer maps I've made under CC-BY-NC-SA.

The -NC- requirement infringes the /most fundamental/ freedom, that to use the work for any purpose.

I have never made anything available under those terms.

**Comment by ihptru** [comment]
Most of those maps were originally uploaded by me and all of them got this cc-by-nc-sa.
That is 484 maps authored by you and other people. I just removed any license definition from all those maps.
