### ISSUE TITLE
Add mod filter to the web for maps.

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA-Resources#281]
The Resource Center site needs a mod filter,browsing maps for specific mods its a pain right now.
Things like mod,terrain type,official rules,player number, are missing right now.just saying.

*for clearing out misunderstandings,i don't mean about hovering the mouse on maps,i mean adding a search box.

**Comment by UberWaffe** [comment]
#193, #23 and #252 refer to similar functionality.

**Comment by UberWaffe** [comment]
You should only close this if you are happy that #193, #23 and #252 indeed cover the functionality that you want.
I'll make a specific comment in #252 to note that there should be tags for the various mods.

**Comment by KOYK** [comment]
thank you!
