### ISSUE TITLE
`tileset` field in map API should not be lower case

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA-Resources#286]
The tileset IDs are case sensitive, so `tileset: "temperat"`, `tileset: "snow"` etc are not valid.
They should be `tileset: "TEMPERAT"`, `tileset: "SNOW"`, etc, to match how they are defined in the map.

**Comment by ihptru** [comment]
fixed code for future maps;
executed script on all existing maps to update field in db.
