### ISSUE TITLE
New uploads parsed with latest playtest by default.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA-Resources#288]
When uploading a map made with the release the upload page could have it set 'parsed with release20151224' by default, after which one can upgrade it using the map page. You don't get an automatic upgrade option when uploading the map parsed with the playtest. Casual map makers will probably be confused when they upload a map and are asked to upgrade the map using the utility program, which they might not bother doing.

e.g. https://www.reddit.com/r/openra/comments/4ds0ug/upgrading_maps/

**Comment by ihptru** [comment]
changed order for now.
