### ISSUE TITLE
Problems with slashes in author names

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA-Resources#298]
For example http://resource.openra.net/maps/19939/ has `by Irnub/CombinE` which redirects to http://resource.openra.net/maps/author/Irnub/CombinE/ which gives a "Page not found" error.

**Comment by dsimmons87** [comment]
This is sorted now with the above linked commit. Happy to close?

**Comment by abcdefg30** [comment]
Yep, thanks. :)
