### ISSUE TITLE
Changing my email

### ISSUE THREAD

**Issue by RadicalEdward2** [OpenRA/OpenRA-Resources#299]
I'm currently in the process of changing my email for all of my accounts and I can't find an option on the Resource Center to change my email address. Could someone help me out with this?

**Comment by ihptru** [comment]
tell me old and new email, or send via IRC...

**Comment by RadicalEdward2** [comment]
old: paduai@kean.edu
new: paduai1993@gmail.com

**Comment by RadicalEdward2** [comment]
Emailed my response from my new email address.

**Comment by ihptru** [comment]
changed.
