### ISSUE TITLE
Lots of lag!

### ISSUE THREAD

**Issue by Wildevuur** [OpenRA/OpenRA-Resources#305]
Maybe a stupid question but i made a map for skirmish (RA) and after 10~15 mins it goes laggy. I have a lot of gems on the map.. Is that the problem or something on hardware?

**Comment by reaperrr** [comment]
When it got laggy, were there a lot of harvesters and other units moving on the map?
OpenRA generally doesn't have a very performant pathfinding, which is (unfortunately) unlikely to change in the forseeable future as we currently don't have any devs with both the skill and time + motivation to fix this.

**Comment by pchote** [comment]
Were you playing vs bots?

**Comment by Wildevuur** [comment]
@reaperrr Yes there moving lots of units arround the map. But how can they make such easy game so laggy?
@pchote Yes i played with bots.

**Comment by dsimmons87** [comment]
@Wildevuur You might be better off raising this issue on the main OpenRA GitHub project here:

https://github.com/OpenRA/OpenRA/issues

This one is just for the resource center where maps are hosted, and isn't really checked for issues in the main game.

**Comment by pchote** [comment]
Closing as this does not apply to the resource center.
