### ISSUE TITLE
Broken links & map sorting options

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA-Resources#321]
The "Most Commented" button results in a "server error (500)".
The dropdown filter "Category:" contains some outdated / no longer existing options.
https://resource.openra.net/maps/

(IRC) ingame.logs.openra.net/(In-Game Chat Logs of OpenRA) link no longer exists.
(IRC) ingame.logs.openra.net/stats/index.html (In-Game Chat of OpenRA stats) link no longer exists.
(Social sites): desura.com/games/openra no longer exists.
(Thirdparty) "OpenRA Server List for Android" link result is "Not Found".
(Thirdparty) Unit costs and tech tree link is more than three years out of date(20150424).
https://resource.openra.net/links/

**Comment by pchote** [comment]
Probably best to completely remove https://resource.openra.net/links/.

**Comment by pchote** [comment]
Fixed by #339.
