### ISSUE TITLE
Duplicates are not detected if uploader is different

### ISSUE THREAD

**Issue by jrb0001** [OpenRA/OpenRA-Resources#349]
If I upload a map and then try to upload the same one again, it fails with `Failed. You've already uploaded this map.`. If I upload a map which was previously uploaded by somebody else, it succeeds.

**Comment by abcdefg30** [comment]
I suppose this is somewhat expected behaviour as we have a button to show duplicates.

**Comment by jrb0001** [comment]
Yes, but that button isn't easy to find if you don't know where to look. Also you can only see it after the upload completed.

**Comment by pchote** [comment]
This appears to be intentional behaviour, but I don't understand the motivation for this and the duplicates button.

We can think about changing this after the uploading code has been rewritten.
