### ISSUE TITLE
Comments system [$10]

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA-Resources#40]
On the old site, users can comment other submissions (maps, units, mods...).
I think it would be cool to be notififed if someone has commented my work.

The number of comments could be displayed at the top, next to Profile https://github.com/ihptru/OpenRA-Content-Engine/issues/12#issuecomment-31403707 and Logout.

Mockup:
![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313733323737332f313832383535332f30393362643763612d373235642d313165332d383964362d6164326235366534643336642e706e67](https://cloud.githubusercontent.com/assets/1732773/2938244/790981a4-d8fd-11e3-9b9b-90e2f30bb7dc.png)

* The first image above shows a user who has 4 unread comments (note that this notification would only be viewable after logging in).
* In the second image: If the user is logged in and has no comment, then it will show "(0) comments".

**Comment by ihptru** [comment]
![sn114](https://cloud.githubusercontent.com/assets/791864/12325710/26e5f466-badd-11e5-9ca1-630528dd9d97.png)

**Comment by ihptru** [comment]
https://github.com/ihptru/OpenRA-Resources/commit/c2a6823699be9c7d77f14d9833cf0ffce9b1093c
![sn115](https://cloud.githubusercontent.com/assets/791864/12349009/52daced4-bb7d-11e5-9b9f-e0a282501bd8.png)

**Comment by ihptru** [comment]
implemented `comments by user` page accessible via own profile.

![sn116](https://cloud.githubusercontent.com/assets/791864/12393332/164a283a-be06-11e5-8b89-a4911ca8cbab.png)
