### ISSUE TITLE
More links (categories) in the menu

### ISSUE THREAD

**Issue by xan2622** [OpenRA/OpenRA-Resources#46]
I know you have added palettes on your website in https://github.com/ihptru/OpenRA-Content-Engine/commit/01cdc957ad3997eb011dc9b5a08e286100a016b5 but I think you should make them available for download as well. I am sure some artists will like to have a place to find them all easily.

On the old content site, you added a Gallery to show users' submitted screenshots.
I think you could add a link in this drop-down menu:
![screenshot002](https://f.cloud.github.com/assets/1732773/1890732/7c08949c-7a31-11e3-94a5-e5f50ef7622a.png)

A simple drop-down menu like this one would help you display more content stuff, while not cluttering the menu.

**Comment by x-a-n-a-x** [comment]
I still hope you will allow modders to download the pack of palette files I sent you.
It should be available from the menu, at the top. Other > Palettes
