### ISSUE TITLE
Create a Firefox Search engine and publish it at mycroftproject.com

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA-Resources#52]
I think you should create a **Firefox Search engine** and publish it at http://mycroftproject.com 

You could also add some explainations/details to help Firefox users understand what it is about.
With this search engine, firefox users will be able to search the new content site directly from their Search bar! 

The page to submit the plugin:
http://mycroftproject.com/submitos.html

Some docs/tutorials to create the Search Engine plugin:
* http://www.opensearch.org/Home

* https://developer.mozilla.org/en-US/Add-ons/Creating_OpenSearch_plugins_for_Firefox?redirectlocale=en-US&redirectslug=Creating_OpenSearch_plugins_for_Firefox

**Comment by ihptru** [comment]
only if someone else will to support this; to finish website search functionality and support it is a priority.
