### ISSUE TITLE
Drag and drop Django jquery upload plugin

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA-Resources#6]
It would be cool if the website allowed to upload file with a simple drag and drop.

Here is a project that could be interesting:
https://github.com/sigurdga/django-jquery-file-upload

Demo:
http://blueimp.github.io/jQuery-File-Upload/

**Comment by ihptru** [comment]
does not look like it fits right now, as user still have to select parser, write info, choose license.
